name: nx-monorepo
description: A project using an Nx monorepo.
main: dist/index.js
runtime:
  name: nodejs
  options:
    typescript: false
template:
  config:
    aws:region:
      description: The AWS region to deploy into
      default: us-west-2