# Generated by Django 3.1 on 2020-08-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_zestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zestion',
        ),
    ]
