[[constraint]]
  version = "v1.13.0"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = "v1.26.0"
  name = "github.com/pulumi/pulumi-aws"

[[constraint]]
  version = "v1.4.1-0.20191106224347-f1bd0923b832"
  name = "github.com/stretchr/testify"

[prune]
  go-tests = true
  unused-packages = true
