name: Command dispatch for testing
on:
  issue_comment:
    types:
    - created
    - edited
jobs:
  command-dispatch-for-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Run Build
      uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4
      with:
        commands: run-tests
        issue-type: pull-request
        permission: write
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        repository: pulumi/examples
        token: ${{ secrets.EVENT_PAT }}
